// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkxPSFg3nEaOz1HSYarJQf2CWlLHMNNt4',
    appId: '1:466715757736:web:53df5d6bffe77bde8c069d',
    messagingSenderId: '466715757736',
    projectId: 'flutter-chat-app-cf269',
    authDomain: 'flutter-chat-app-cf269.firebaseapp.com',
    storageBucket: 'flutter-chat-app-cf269.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1EmPjYa2LH-mHLCgQy6Xm0_wdM_XXpYU',
    appId: '1:466715757736:android:ef61eabc7de346eb8c069d',
    messagingSenderId: '466715757736',
    projectId: 'flutter-chat-app-cf269',
    storageBucket: 'flutter-chat-app-cf269.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMFmcRtTyQNrG2VfDp7A8CUfbgnOP9l6g',
    appId: '1:466715757736:ios:7531a4716c24d0898c069d',
    messagingSenderId: '466715757736',
    projectId: 'flutter-chat-app-cf269',
    storageBucket: 'flutter-chat-app-cf269.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMFmcRtTyQNrG2VfDp7A8CUfbgnOP9l6g',
    appId: '1:466715757736:ios:6bd7538ccd97477c8c069d',
    messagingSenderId: '466715757736',
    projectId: 'flutter-chat-app-cf269',
    storageBucket: 'flutter-chat-app-cf269.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
